import './globals.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='bg-blue-500' suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  )
}
